---
output: github_document
---

# Assignment guide

## General information

This is a guide that explains how you should submit your assignments. Please read it before you start working on your assignments, this way you can save a lot of time for yourself. If you have any more question after reading this guide please write Marton Kovacs at marton.balazs.kovacs@gmail.com.

__Note: You only have to finish two assignments of your choosing. You do not have to do all of them.__

## How to submit the assignemnts

Submitting the assignments will require the use of Git and Github. There is a detailed tutorial on how to use Git with R that you can find here: https://happygitwithr.com/

  * To work on your assignments please fork this repository.
  * Work on each assignment in the .Rmd files in the "assignment/" folder on your computer.
  * Stage and commit your changes. (Pro tip: Do this frequently.)
  * Push the changes to your forked project. (Also do this frequently, e.g. after each assignment).
  * If you are done, create a pull request, and assign Tamas and Marton as reviewers
  
__Have Fun!__
  

